### ISSUE TITLE
Set up backend

### ISSUE THREAD

**Issue by osycon** [chingu-voyage7/Bears-Team-19#2]

**Comment by chsanch** [comment]
Hi, I'm setting up the backend, using the DB model described in http://chsanch.info/db_docs
To provide a REST API I'm using https://postgrest.org/, which exposes a complete RESTful API using the database model, so any change added to the schema will be reflected immediately in the API.
You can access the API at http://api.chsanch.info, I recommend to use Postman, and do request against the API. Making GET request as a anonymous user are allowed at the moment, but to do any other action (POST, DELETE, PUT, etc) you will need a JWT Token. Please send me your emails to invite you to join a Team in Postman where we can share API Requests as examples and to test them in order to organise the client requests workflow.
